# -*- coding: utf-8 -*-
"""create_irish_midi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HB7nQwXYt8Yh49nb2oqMxl32kEfYxFEN
"""

import numpy as np

from google.colab import drive

drive.mount('/content/gdrive')

data_path = "/content/gdrive/My Drive/Applied Deep Learning/Outputs/"

new_songs_raw = np.load(data_path + 'new_songs.npy')

new_songs_raw.shape

"""## Generate MIDI"""

from music21 import instrument, note, stream, chord

def create_midi_irish(prediction_output, number, output_path):
    """ convert the output from the prediction to notes and create a midi file
        from the notes """
    offset = 0
    output_notes = []

    # create note and chord objects based on the values generated by the model
    for pattern in prediction_output:
        
        current_note = pattern[0]
        velocity = pattern[1]
        duration = pattern[2]
        
        notes = []
        new_note = note.Note(int(current_note))
        new_note.storedInstrument = instrument.Piano()
        notes.append(new_note)
        new_chord = chord.Chord(notes)
        new_chord.offset = offset
        output_notes.append(new_chord)   
            
        offset += duration

    midi_stream = stream.Stream(output_notes)

    midi_stream.write('midi', fp=output_path+'irish_output%d.mid' % number)

output_path = "/content/gdrive/My Drive/Applied Deep Learning/Irish Output/"

for k in range(new_songs_raw.shape[0]):
  create_midi_irish(new_songs_raw[k], k, output_path)